CREATE TABLE users (
  USER_SEQ int NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(100) NOT NULL,
  USER_ID varchar(100) NOT NULL,
  USER_PASSWORD varchar(50) NOT NULL,
  USER_PROFILE_IMAGE_URL varchar(500) DEFAULT NULL,
  USER_REGISTER_DATE date DEFAULT NULL,
  PRIMARY KEY (USER_SEQ),
  UNIQUE KEY USER_ID_UNIQUE (USER_ID)
);

CREATE TABLE board (
  BOARD_ID int NOT NULL AUTO_INCREMENT,
  USER_SEQ int NOT NULL,
  TITLE varchar(500) DEFAULT NULL,
  CONTENT text,
  REG_DT datetime DEFAULT NULL,
  READ_COUNT int DEFAULT '0',
  PRIMARY KEY (BOARD_ID),
  KEY FK_USER_idx (USER_SEQ),
  CONSTRAINT FK_USER FOREIGN KEY (USER_SEQ) REFERENCES users (USER_SEQ)
);

